In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from matplotlib import pyplot as plt

In [2]:
data = {
    'RAM':[1,2,4,6,8,12,16,20,28,32],
    'Battery_Capacity':[2200,2400,3000,3200,3800,4000,4200,4800,5000,6000],
    'PriceRange':[0,0,0,1,1,1,1,1,2,2]
}

df = pd.DataFrame(data)

In [3]:
x = df[['RAM','Battery_Capacity']]
y = df['PriceRange']

In [4]:
k = 3
knn = KNeighborsClassifier(n_neighbors=k)

knn.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [5]:
new_data = np.array([[4,5000]])
prediction = knn.predict(new_data)

if prediction == 0:
  print("Price Range is:15000-25000")

elif prediction == 1:
  print("Price Range is:25000-30000")
else:
  print("Price Range is:50000 or above")

Price Range is:25000-30000


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = {
    'RAM':[1,2,4,6,8,12,16,20,28,32],
    'Battery_Capacity':[2200,2400,3000,3200,3800,4000,4200,4800,5000,6000],
    'PriceRange':[0,0,0,1,1,1,1,1,2,2]
}

df = pd.DataFrame(data)

x = df[['RAM','Battery_Capacity']]
y = df['PriceRange']


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


lr = LinearRegression()
lr.fit(X_train, y_train)


y_pred = lr.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')


print('Predictions for the test set:')
for i, (true, pred) in enumerate(zip(y_test, y_pred)):
    print(f'Sample {i}: True value = {true}, Predicted value = {pred:.2f}')

if prediction == 0:
  print("Price Range is:15000-25000")

elif prediction == 1:
  print("Price Range is:25000-30000")
else:
  print("Price Range is:50000 or above")


Mean Squared Error: 0.16643977988713163
R-squared: 0.7503403301693026
Predictions for the test set:
Sample 0: True value = 2, Predicted value = 1.30
Sample 1: True value = 0, Predicted value = 0.09
Sample 2: True value = 1, Predicted value = 0.94
Price Range is:25000-30000


In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = {
    'RAM':[1,2,4,6,8,12,16,20,28,32],
    'Battery_Capacity':[2200,2400,3000,3200,3800,4000,4200,4800,5000,6000],
    'PriceRange':[0,0,0,1,1,1,1,1,2,2]
}

df = pd.DataFrame(data)

x = df[['RAM','Battery_Capacity']]
y = df['PriceRange']



X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


lr = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
lr.fit(X_train, y_train)


y_pred = lr.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

# Predictions for the test set
print('Predictions for the test set:')
for i, (true, pred) in enumerate(zip(y_test, y_pred)):
    print(f'Sample {i}: True value = {true}, Predicted value = {pred}')

if prediction == 0:
  print("Price Range is:15000-25000")

elif prediction == 1:
  print("Price Range is:25000-30000")
else:
  print("Price Range is:50000 or above")


Accuracy: 0.6666666666666666
Confusion Matrix:
[[1 0 0]
 [0 1 0]
 [0 1 0]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.50      0.67      0.56         3
weighted avg       0.50      0.67      0.56         3

Predictions for the test set:
Sample 0: True value = 2, Predicted value = 1
Sample 1: True value = 0, Predicted value = 0
Sample 2: True value = 1, Predicted value = 1
Price Range is:25000-30000


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = {
    'RAM':[1,2,4,6,8,12,16,20,28,32],
    'Battery_Capacity':[2200,2400,3000,3200,3800,4000,4200,4800,5000,6000],
    'PriceRange':[0,0,0,1,1,1,1,1,2,2]
}

df = pd.DataFrame(data)

x = df[['RAM','Battery_Capacity']]
y = df['PriceRange']


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

# Predictions for the test set
print('Predictions for the test set:')
for i, (true, pred) in enumerate(zip(y_test, y_pred)):
    print(f'Sample {i}: True value = {true}, Predicted value = {pred}')

if prediction == 0:
  print("Price Range is:15000-25000")

elif prediction == 1:
  print("Price Range is:25000-30000")
else:
  print("Price Range is:50000 or above")

Accuracy: 0.6666666666666666
Confusion Matrix:
[[1 0 0]
 [0 1 0]
 [0 1 0]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.50      0.67      0.56         3
weighted avg       0.50      0.67      0.56         3

Predictions for the test set:
Sample 0: True value = 2, Predicted value = 1
Sample 1: True value = 0, Predicted value = 0
Sample 2: True value = 1, Predicted value = 1
Price Range is:25000-30000


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = {
    'RAM':[1,2,4,6,8,12,16,20,28,32],
    'Battery_Capacity':[2200,2400,3000,3200,3800,4000,4200,4800,5000,6000],
    'PriceRange':[0,0,0,1,1,1,1,1,2,2]
}

df = pd.DataFrame(data)

x = df[['RAM','Battery_Capacity']]
y = df['PriceRange']


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)


y_pred = rfc.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

print('Predictions for the test set:')
for i, (true, pred) in enumerate(zip(y_test, y_pred)):
    print(f'Sample {i}: True value = {true}, Predicted value = {pred}')

if prediction == 0:
  print("Price Range is:15000-25000")

elif prediction == 1:
  print("Price Range is:25000-30000")
else:
  print("Price Range is:50000 or above")


Accuracy: 0.6666666666666666
Confusion Matrix:
[[1 0 0]
 [0 1 0]
 [0 1 0]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.50      0.67      0.56         3
weighted avg       0.50      0.67      0.56         3

Predictions for the test set:
Sample 0: True value = 2, Predicted value = 1
Sample 1: True value = 0, Predicted value = 0
Sample 2: True value = 1, Predicted value = 1
Price Range is:25000-30000


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
